name: Keep Render Backend Awake

on:
  schedule:
    # Runs every 14 minutes from 9:15 AM â€“ 10:30 PM IST
    - cron: "*/14 3-17 * * *"
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to backend
        run: |
          curl -s https://taskboard-grantify-api.onrender.com/health || echo "Ping failed"
